baseurl = "https://1rvinn.github.io/"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "re-terminal"
pagination.pagerSize = 5

# Set the home page as default
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "home"

  # ["orange", "blue", "red", "green", "pink", "paper"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 9

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "Table of Contents" # default
  # you can set a banner on the top of the page with a call to action
  # defaults: dismissible = false; URL is optional
  # [params.banner]
  # dismissible = false
  # text = "Check it out on GitHub"
  # url = "https://github.com/mirus-ua/hugo-theme-re-terminal"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en.params]
    languageName = "English"
    title = "aperture."
    subtitle = "it's the experience that matters."
    owner = "irvin sachdeva"
    keywords = "test"
    copyright = "Â© 2025 - irvin sachdeva"
    menuMore = "show more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "page not found..."
    missingBackButtonLabel = "back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "aperture."
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "crude"
        name = "crude"
        url = "/crude"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "eureka"
        name = "eureka!"
        url = "/eureka"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "build"
        name = "build"
        url = "/build"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "canvas"
        name = "canvas"
        url = "/canvas"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "read_to_reach"
        name = "read to reach"
        url = "/readtoreach"
        weight = 6
      [[languages.en.menu.main]]
        identifier = "fcket_list"
        name = "f*cket list"
        url = "/fcketlist"
        weight = 7

[permalinks]
  home = "/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[aliases]
  "/" = "/home"